
[general]
	adjust_hurt_camera_effect = 14.0

	[general.damage_types]
		adjust_hurt_camera_effect_in_lava = 14.0
		adjust_hurt_camera_effect_while_burning = 14.0
		adjust_hurt_camera_effect_wwhile_burning = 14

